services:

  lockbox.web:
    image: ${DOCKER_REGISTRY-}lockboxweb
    container_name: lockbox.web
    build:
      context: .
      dockerfile: src/Lockbox.Web/Dockerfile
    ports:
      - "6363:6363"
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081

  lockbox.database:
    image: postgres:latest
    container_name: lockbox.database
    environment:
      - POSTGRES_PASSWORD=Lockbox
      - POSTGRES_USER=Lockbox
      - POSTGRES_DB=Lockbox
    volumes:
      - ./.containers/lockbox-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  lockbox.smtp:
    image: "rnwood/smtp4dev"
    container_name: lockbox.smtp
    restart: unless-stopped
    ports:
      - "5011:80"